# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: ecb3f93
_src_path: .
author_email: johndoe@example.com
author_name: John Doe
current_version: 2024.8.1
django_versions:
- '4.2'
- '5.0'
docs_domain: westervelt.dev
github_owner: example_owner
github_repo: calver-mminc1-project
module_name: calver_mminc1_project
package_description: An example Django package
package_name: calver-mminc1-project
python_versions:
- '3.8'
- '3.9'
- '3.10'
- '3.11'
- '3.12'
test_django_main: true
versioning_scheme: CalVer (YYYY.MM.INC1)
