# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 785caf9
_src_path: .
author_email: johndoe@example.com
author_name: John Doe
current_version: '2024.1'
django_versions:
- '3.2'
- '4.2'
- '5.0'
docs_domain: westervelt.dev
github_owner: example_owner
github_repo: calver-inc1-project
module_name: calver_inc1_project
package_description: An example Django package
package_name: calver-inc1-project
python_versions:
- '3.8'
- '3.9'
- '3.10'
- '3.11'
- '3.12'
test_django_main: true
versioning_scheme: CalVer (YYYY.INC1)
