# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: ed73105
_src_path: .
author_email: johndoe@example.com
author_name: John Doe
current_version: 0.1.0
django_versions:
- '3.2'
- '4.2'
- '5.0'
docs_domain: westervelt.dev
github_owner: example_owner
github_repo: semver-project
module_name: semver_project
package_description: An example Django package
package_name: semver-project
python_versions:
- '3.8'
- '3.9'
- '3.10'
- '3.11'
- '3.12'
test_django_main: true
versioning_scheme: SemVer
