name: examples

on:
  push:
    branches: [main]
    paths:
      - "examples/**.yml"
      - "src/**"
      - "copier.yml"
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          version: "0.4.x"

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"

      - name: Generate examples
        run: |
          just generate-examples

      - name: Get SHA of push commit
        if: github.event != 'workflow_call'
        id: shortsha
        run: echo "shortsha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Commit and push if examples have changed
        if: github.event != 'workflow_call'
        run: |-
          git add -A
          git commit -m "Regenerated examples for ${{ steps.shortsha.outputs.shortsha }}" || exit 0
          git push
