name: test

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: westerveltco/setup-ci-action@v0
        with:
          python-version: "3.8"
          python-requirements: requirements-dev.lock
          use-uv: true

      - name: Run tests
        run: |
          python -m pytest

  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v1

      - uses: westerveltco/setup-ci-action@v0
        with:
          python-version: "3.8"
          python-requirements: requirements-dev.lock
          use-uv: true

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"

      - name: Generate examples
        run: |
          just generate-examples
